biolib_version: 2
modules:
    main:
        image: 'local-docker://cbh2021:latest'
        command: python CNN.py
        working_directory: /home/biolib/
        input_files:
            - COPY / /home/biolib/
        output_files:
            - COPY /home/biolib/ /
        source_files:
            - COPY / /home/biolib/
